parameters:
  publisher.test:
    timeout: 100000

# define all the types of publishers we need to use in the application
services:
  publisher.demo:
    class: \Amqp\Util\Publisher\Simple
    calls:
      - [setExchange, [@exchange.testExchange]]
      - [setConfiguration, [%publisher.test%]]
