parameters:
  listener.test:
    onProcessError: requeue
    maxRequeue: 3
    bulkAck: 0

# configures the actual listeners we will need to use in the application, attaching the monitors and the processors
# so that we can get a fully configured instance from the factory
services:
  listener.test:
    class: \Amqp\Util\Listener\Simple
    calls:
      # attach the monitors
      - [attachMonitor, ["@monitor.memory"]]
      - [attachMonitor, ["@monitor.fileChange"]]
      - [attachMonitor, ["@monitor.memory"]]
      # attach the processor
      - [setProcessor, ["@processor.test"]]
      # queue
      - [setQueue, [@queue.testQueue]]
      # config
      - [setConfiguration, [%listener.test%]]

  listener.dateTime:
    class: \Amqp\Util\Listener\Simple
    arguments:
      - @queue.dateTimeQueue
      - %listener.test%
    calls:
      # attach the monitors
      - [attachMonitor, ["@monitor.memory"]]
      - [attachMonitor, ["@monitor.fileChange"]]
      - [attachMonitor, ["@monitor.memory"]]
      # attach the processor
      - [setProcessor, ["@processor.dateTime"]]
      # queue
      - [setQueue, [@queue.dateTimeQueue]]
      # config
      - [setConfiguration, [%listener.test%]]
