services:
  queue.testQueue:
    factory: ["@amqp.builder.factory", queue]
    arguments:
      - testQueue

  queue.dateTimeQueue:
      factory: ["@amqp.builder.factory", queue]
      arguments:
        - dateTimeQueue
