parameters:
  listener.test:
    onProcessError: requeue
    maxRequeue: 3
    bulkAck: 0

services:
  # define all the types of listeners we need to use in the application
  listener.demo:
    class: \Amqp\Util\Listener\Rpc
    calls:
      # attach the monitors
      - [attachMonitor, ["@monitor.memory"]]
      - [attachMonitor, ["@monitor.fileChange"]]
      - [attachMonitor, ["@monitor.memory"]]
      # attach the processor
      - [setProcessor, ["@processor.test"]]
      # queue
      - [setQueue, [@queue.test]]
      # config
      - [setConfiguration, [%listener.test%]]