parameters:
  publisher.test:
    timeout: 100000

services:
  # define all the types of publishers we need to use in the application
  publisher.demo:
    class: \Amqp\Util\Publisher\Rpc
    calls:
      - [attach, ["@processor.rpc"]]
      - [setExchange, [@exchange.test]]
      - [setConfiguration, [%publisher.test%]]
